@URL = http://localhost:4000
@TYPE = /api/admin
###
GET {{URL}}{{TYPE}}/check
Content-Type: application/json

###
DELETE {{URL}}{{TYPE}}/checkdelete/1234566/abcdfv
Content-Type: application/json

###
POST {{URL}}{{TYPE}}/check
Content-Type: application/json

{
    "name":"admin",
    "mailId":"admin@boiler.com",
    "age":25,
    "password":"qwe$7500",
    "phoneNo":9042141018,
}